export const START_INGREDIENTS_FETCH = "START_INGREDIENTS_FETCH";
export const ERROR_INGREDIENTS_FETCH = "ERROR_INGREDIENTS_FETCH";
export const SUCCESS_INGREDIENTS_FETCH = "SUCCESS_INGREDIENTS_FETCH";
export const OPEN_INGREDIENT_DETAILS = "OPEN_INGREDIENT_DETAILS";
export const CLOSE_INGREDIENT_DETAILS = "CLOSE_INGREDIENT_DETAILS";
