export const SUCCESS_LOGIN: "SUCCESS_LOGIN" = "SUCCESS_LOGIN";
export const ERROR_LOGIN: "ERROR_LOGIN" = "ERROR_LOGIN";
export const START_LOGIN: "START_LOGIN" = "START_LOGIN";
export const LOGOUT: "LOGOUT" = "LOGOUT";
export const LOGIN_CHECKED: "LOGIN_CHECKED" = "LOGIN_CHECKED";
