export const START_ORDER_POST: "START_ORDER_POST" = "START_ORDER_POST";
export const ERROR_ORDER_POST: "ERROR_ORDER_POST" = "ERROR_ORDER_POST";
export const SUCCESS_ORDER_POST: "SUCCESS_ORDER_POST" = "SUCCESS_ORDER_POST";
export const CLOSE_ORDER_MODAL: "CLOSE_ORDER_MODAL" = "CLOSE_ORDER_MODAL";
