export const REFRESH_TOKEN_START: "REFRESH_TOKEN_START" = "REFRESH_TOKEN_START";
export const REFRESH_TOKEN_SUCCESS: "REFRESH_TOKEN_SUCCESS" =
  "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_ERROR: "REFRESH_TOKEN_ERROR" = "REFRESH_TOKEN_ERROR";
