export const SHOW_REQUEST_INFO: "SHOW_REQUEST_INFO" = "SHOW_REQUEST_INFO";
export const SHOW_REQUEST_ERROR_INFO: "SHOW_REQUEST_ERROR_INFO" =
  "SHOW_REQUEST_ERROR_INFO";
export const CLOSE_REQUEST_INFO: "CLOSE_REQUEST_INFO" = "CLOSE_REQUEST_INFO";
