export const SUCCESS_RESTORE_PASS = "SUCCESS_RESTORE_PASS";
export const ERROR_RESTORE_PASS = "ERROR_RESTORE_PASS";
export const START_RESTORE_PASS = "START_RESTORE_PASS";
export const RESET_REQUEST_ACCEPT = "RESET_REQUEST_ACCEPT";
